#!/bin/sh
echo "deb http://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
sudo apt-get update
sudo apt-get install sbt -y --force-yes
nohup sbt run > sbt.log &
open-port 8585
